name: Prettier

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  prettier:
    runs-on: ubuntu-latest
    name: Check Code Style
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check Prettier
        run: npm run format:check

      - name: Check Eslint
        run: npm run lint
